name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            # Patch imagePullPolicy to Always (run once)
            kubectl patch deployment devincoopers-space-deployment \
              -n devincooper \
              -p '{"spec":{"template":{"spec":{"containers":[{"name":"devincoopers-space","imagePullPolicy":"Always"}]}}}}'

            # Deploy latest SHA-tagged image
            kubectl set image deployment/devincoopers-space-deployment \
              devincoopers-space=ghcr.io/gymtechlaundry/devincoopers-space:${{ github.sha }} \
              -n devincooper

            # Wait for rollout completion
            kubectl rollout status deployment/devincoopers-space-deployment -n devincooper